version: "3.7"
services:
    pg:
        container_name: api-lemobs_pg
        image: postgres
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: db
        volumes:
            - ./db_dump/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
            - pg_data_volume:/var/lib/postgres/data #o volume pg_data_volume será criado e armazenará todos os dados da base
        ports:
            - '5432:5432'
        restart: unless-stopped
        networks:
            - pg_net

#Mais fácil para visualizar os dados rapidamente    
    pgadmin:
        container_name: api-lemobs_pgadmin
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: pgadmin@email.com
            PGADMIN_DEFAULT_PASSWORD: pgadminpw
        ports:
            - '52278:80'
        depends_on: 
            - pg
        networks:
            - pg_net

    api:
        container_name: api-lemobs_api
        build: .
        environment:
            DB_HOST: pg
        depends_on: 
            - pg
        ports:
            - '4000:3000'
        volumes:
            - .:/usr/app
            - /usr/app/node_modules
        command: npm run start:dev
        
        restart: unless-stopped

        networks:
            - pg_net

networks: 
    pg_net:
        driver: bridge
volumes:
    pg_data_volume: